name: rag
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.8.0=py310hc6cd4ac_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - flask=3.0.2=pyhd8ed1ab_0
  - gunicorn=21.2.0=py310hff52083_1
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.17.2=pyh41d4057_0
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py310hff52083_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=19_linux64_openblas
  - libcblas=3.9.0=19_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libgomp=13.2.0=h807b86a_2
  - liblapack=3.9.0=19_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.44.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - openssl=3.2.1=hd590300_1
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=pyhd8ed1ab_0
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py310h2372a71_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - python=3.10.13=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pyzmq=25.1.1=py310h795f18f_2
  - readline=8.2=h8228510_1
  - scikit-learn=1.3.2=py310h1fdf081_1
  - scipy=1.11.3=py310hb13e2d6_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.3.3=py310h2372a71_1
  - traitlets=5.13.0=pyhd8ed1ab_0
  - wcwidth=0.2.9=pyhd8ed1ab_0
  - werkzeug=3.0.2=pyhd8ed1ab_0
  - wheel=0.41.3=pyhd8ed1ab_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - pip:
      - accelerate==0.24.1
      - aiofiles==23.2.1
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - altair==5.1.2
      - annotated-types==0.6.0
      - anyio==3.7.1
      - asgiref==3.8.1
      - astor==0.8.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - backoff==2.2.1
      - bcrypt==4.0.1
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.1
      - build==1.2.1
      - cachetools==5.3.2
      - cchardet==2.1.7
      - certifi==2024.2.2
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - chroma-hnswlib==0.7.3
      - chromadb==0.4.24
      - clickhouse-connect==0.7.7
      - coloredlogs==15.0.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==3.0.5
      - dataclasses-json==0.5.14
      - dataclasses-json-speakeasy==0.5.11
      - datasets==2.14.6
      - deprecated==1.2.14
      - dill==0.3.7
      - distro==1.9.0
      - duckdb==0.9.2
      - emoji==2.10.1
      - faker==19.13.0
      - fastapi==0.110.1
      - ffmpy==0.3.1
      - filelock==3.13.1
      - filetype==1.2.0
      - flatbuffers==23.5.26
      - fonttools==4.44.0
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - gekko==1.0.6
      - google-auth==2.23.4
      - googleapis-common-protos==1.61.0
      - gradio==4.27.0
      - gradio-client==0.15.1
      - greenlet==3.0.1
      - grpcio==1.59.2
      - h11==0.14.0
      - httpcore==1.0.1
      - httptools==0.6.1
      - httpx==0.25.1
      - huggingface-hub==0.22.2
      - humanfriendly==10.0
      - idna==3.6
      - importlib-resources==6.1.0
      - instructorembedding==1.0.1
      - jinja2==3.1.2
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpointer==2.4
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - kiwisolver==1.4.5
      - kubernetes==29.0.0
      - langchain==0.1.16
      - langchain-community==0.0.33
      - langchain-core==0.1.44
      - langchain-text-splitters==0.0.1
      - langchain-util==0.1.7
      - langchainplus-sdk==0.0.20
      - langdetect==1.0.9
      - langsmith==0.1.48
      - lxml==5.1.0
      - lz4==4.3.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.20.2
      - matplotlib==3.8.1
      - mdurl==0.1.2
      - mmh3==4.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - nltk==3.8.1
      - numexpr==2.10.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.52
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - onnxruntime==1.16.1
      - openai==1.12.0
      - openapi-schema-pydantic==1.2.4
      - opentelemetry-api==1.20.0
      - opentelemetry-exporter-otlp-proto-common==1.20.0
      - opentelemetry-exporter-otlp-proto-grpc==1.20.0
      - opentelemetry-instrumentation==0.41b0
      - opentelemetry-instrumentation-asgi==0.41b0
      - opentelemetry-instrumentation-fastapi==0.41b0
      - opentelemetry-proto==1.20.0
      - opentelemetry-sdk==1.20.0
      - opentelemetry-semantic-conventions==0.41b0
      - opentelemetry-util-http==0.41b0
      - orjson==3.10.1
      - overrides==7.4.0
      - pandas==1.5.3
      - pandasai==1.5.19
      - pdf2image==1.16.3
      - peft==0.6.0
      - pillow==10.1.0
      - posthog==3.0.2
      - protobuf==4.25.0
      - pulsar-client==3.3.0
      - pyarrow==14.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycryptodome==3.19.0
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pydub==0.25.1
      - pyparsing==3.1.1
      - pypdf==3.17.0
      - pypika==0.48.9
      - pyproject-hooks==1.0.0
      - python-dotenv==1.0.0
      - python-iso639==2024.2.7
      - python-magic==0.4.27
      - python-multipart==0.0.9
      - python-pptx==0.6.23
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - rapidfuzz==3.6.1
      - referencing==0.30.2
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.6.0
      - rouge==1.0.1
      - rpds-py==0.12.0
      - rsa==4.9
      - ruff==0.3.7
      - safetensors==0.4.2
      - semantic-version==2.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.23
      - starlette==0.37.2
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tokenizers==0.15.2
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.0
      - torch==2.1.0
      - torchvision==0.16.0
      - tqdm==4.66.2
      - transformers==4.37.2
      - triton==2.1.0
      - typer==0.12.3
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - unstructured==0.13.0
      - unstructured-client==0.18.0
      - urllib3==2.2.1
      - uvicorn==0.24.0.post1
      - uvloop==0.19.0
      - watchfiles==0.21.0
      - websocket-client==1.6.4
      - websockets==11.0.3
      - wikipedia==1.4.0
      - wrapt==1.16.0
      - xformers==0.0.22.post7
      - xlsxwriter==3.2.0
      - xxhash==3.4.1
      - yarl==1.9.2
      - zstandard==0.22.0
